### PR TITLE
Add Menu button to show Publishes, use Auth Token in Claim List

### PR DESCRIPTION
**Pull request by ktprograms**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature

## Fixes

Issue Number: #232

Points:
- `How do I get back to see my uploads?`
- `after publishing something, it went to a screen with "It looks like you have not published content to LBRY yet" with a New Publish button.`

## What is the current behavior?

No way to get back to list of publishes

After publishing nothing is shown due to ClaimListTask failing.

## What is the new behavior?

Menu button to show Publishes

Use Auth Token when listing claims in Publishes fragment.

## Other information

Add ClaimListTask constructor that takes list of types and auth token.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Let's make sure we're passing a page size and pagination . Maybe 10-20 is safe.

**Review by akinwale — APPROVED** [review]
Looks good, thanks. In the future, I'd like to move this to the Library page instead.

**Comment by ktprograms** [comment]
@akinwale Please Rebase merge this, the Claim List pagination commit is quite big so it shouldn't be messed up with the first commit.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
