### PR TITLE
Search improvements

### PR DESCRIPTION
**Pull request by ktprograms**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature

## Fixes

Issue Number: #108 

### Use dark gray color for featured claims

Adds contrast to featured claims in dark mode.

### Improve resolving of featured (matching URL) claims

- Trim leading/trailing whitespace and replace with hyphen between
  words.
- Resolve channel claim from query as well.
- Resolve (and add to list) featured claims only after initial search
  completed.
- Hide duration view when showing featured channel claim.
- Hide other info views when showing "Publish something" item
  (when query does not resolve).
- Remove duplicate percent sign and redundant escape in invalid URI
  regex.

### Lighthouse: Remove resolve=true, run resolve after search

Filter null results and subtract from expected page size (so pagination
works correctly).

Use Ordering.explicit to put claims in correct order after resolve.

### Search: Add Sort By option, use Lighthouse query params

Remove filter functionality from ClaimListAdapter, use Lighthouse query
params instead.

### CODE REVIEW

**Comment by ktprograms** [comment]
Making the featured item background black makes it indistinguishable from other items in dark mode.

**Comment by akinwale** [comment]
@ktprograms Please use a semi-transparent version of the primary colour for the featured item in dark mode. Thanks.

**Comment by ktprograms** [comment]
Diffs in latest push:
https://github.com/OdyseeTeam/odysee-android/pull/288/commits/b8b420fbe01cedf7b528de32080afc5f9ebf56de: [featured-color-fixup.patch.txt](https://github.com/OdyseeTeam/odysee-android/files/9035859/featured-color-fixup.patch.txt)
https://github.com/OdyseeTeam/odysee-android/pull/288/commits/9d621019ffd1e4e791c537c7bd86f2c92af9ec5c: [search-ui-fixup.patch.txt](https://github.com/OdyseeTeam/odysee-android/files/9035865/search-ui-fixup.patch.txt)

**Comment by ktprograms** [comment]
Diff [9d62101...8cf4225](https://github.com/OdyseeTeam/odysee-android/compare/9d621019ffd1e4e791c537c7bd86f2c92af9ec5c..8cf422548ba8e5cfd1cb64d03a0629e7345ccb50):
Use Lighthouse `time_filter` instead of ClaimListAdapter filter.

**Comment by ktprograms** [comment]
I'll fix the merge conflict after it's been reviewed, the conflicting changes in ClaimListAdapter are only removing the unused time filter code, with no logic changes.

**Comment by ktprograms** [comment]
@akinwale Done

**Pull request merged**
