### PR TITLE
Request user to add one channel or sign in when it is required

### PR DESCRIPTION
**Pull request by kekkyojin**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Feature
- [x] Refactoring (no functional changes)

## Fixes

Issue Number: #1

### CODE REVIEW

**Comment by akinwale** [comment]
Is this ready for review yet?

**Comment by kekkyojin** [comment]
No, sorry, Akin. Not yet

**Review by akinwale — CHANGES_REQUESTED** [review]
A couple of issues I noticed:

If I do not have a channel and I create a new one when trying to comment, the drop down list is not updated with the newly created channel.
We should either:
1. Show an infinite loading indicator that channel creation is in progress and may take some time to complete, and keep polling the `channel_list` until the channel has 1 confirmation. 
2. Update the drop down box with the claim result from the `channel_create` event and autoselect the option.

Everything else looks good.

**Comment by kekkyojin** [comment]
I am closing this and making a new one (#136) which could be merged after latest commits to master branch and which only contains a single commit.

**Pull request closed without merging**
