### PR TITLE
Perform automatically a search after 500 milliseconds

### PR DESCRIPTION
**Pull request by kekkyojin**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature

## Fixes

Issue Number: #1 

## What is the current behavior?
User must explicitly request app to perform the search
## What is the new behavior?
App will perform the search request automatically after text had been changed and half a second had elapsed
## Other information
The initial text has also been changed as requested on Alpha bug meta-issue. As it is semantically different from the old -original one, it has been renamed and translations has been removed so translators see there is a new string to be translated.

The request is performed after 500 milliseconds had elapsed. I tried with 300 milliseconds but it looked too much automatic; trying with 1 second was ok but maybe a little too slow. Some other values could also be tested, but current one seems ok to me.

Search fragment has also been simplified. It is now using ConstraintLayout, so RelativeLayout is no longer needed; labels shown when there is no query or there are no results are now using the same TextView. This simplifies the layout without making code more difficult, as there are just a few places where that TextView was needed.

### CODE REVIEW

**Comment by akinwale** [comment]
I'd like to hold off on this for now. Some users were complaining about the behaviour on iOS so we disabled auto search. Maybe we can make this an optional setting that can be toggled on.

**Comment by kekkyojin** [comment]
I have converted this into a draft again until the feature has been finally accepted to be added and to avoid accidental merging of this code.

**Comment by akinwale** [comment]
@kekkyojin With the settings page restored in the latest code, can we update this PR to allow autosearch be a setting that can be toggled?

**Review by akinwale — APPROVED** [review]
Looks good.

**Pull request merged**
