### PR TITLE
Allow user to remove or clear items from its History

### PR DESCRIPTION
**Pull request by kekkyojin**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Feature

## Fixes

Issue Number: #91

## What is the current behavior?
User cannot remove a single item or all of them from the list on Library tab
## What is the new behavior?
Now it can
## Other information
Library fragment has been refactored to use ConstraintLayout in order to acommodate the Clear All button

### CODE REVIEW

**Review by akinwale — CHANGES_REQUESTED** [review]
A couple of changes:
* The Clear All button is out of place. Can we add this as an option to the action menu instead?
* Let's display a confirmation dialog after the user chooses to delete items. before actually performing the delete.

Looks good otherwise. Thanks.

**Comment by kekkyojin** [comment]
> * The Clear All button is out of place. Can we add this as an option to the action menu instead?

I assume you are refering to the toolbar, not the action mode one?

> * Let's display a confirmation dialog after the user chooses to delete items. before actually performing the delete.

My fault. At the end I didn’t add the confirmation dialog

**Comment by kekkyojin** [comment]
I am only adding the Clear All drawable as a vector file because since Android API Level 21 there is no need to use regular drawables

**Review by akinwale — CHANGES_REQUESTED** [review]
We also need this confirmation dialog when trying to delete a single item.

Everything else looks good. Once this is fixed, you can merge. Thanks.

**Pull request merged**
