### PR TITLE
Add authentication token to preferences_get call

### PR DESCRIPTION
**Pull request by kekkyojin**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix

## What is the current behavior?
The call to get preferences is throwing an exception because authentication token is not send along the request
## What is the new behavior?
This PR fixes that

### CODE REVIEW

**Comment by akinwale** [comment]
I already fixed this in a previous commit.

**Comment by kekkyojin** [comment]
That was for saving the state, not for loading it. There is an exception about loading user state in logcat

**Comment by akinwale** [comment]
There was a later one: https://github.com/OdyseeTeam/odysee-android/commit/78e22ad2eba7ada968d2a5364b604092f64f9b18 :)

**Comment by kekkyojin** [comment]
Your commit fixed it when calling saveSharedUserState() method on MainActivity.

Mine fixed it when calling loadSharedUserState() method on MainActivity.

Without this PR applied, there is an exception on logical, even when running a build containing latest commit from today. This PR fixes it.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
